### ISSUE TITLE
Larger input sets

### ISSUE THREAD

**Issue by trinayan** [chai-benchmarks/chai#11]
Hi,

Apart from the benchmarks where the user can specify the size of the data are there any  larger input sources available for the other benchmarks where the user passes a file? Thank you

Best,
Trinayan

**Comment by el1goluj** [comment]
Hi Trinayan,

For CEDD and CEDT, you can generate frames from any video using the utils folder.
For BFS and SSSP, you can potentially use any graph, but you might need to perform format conversion, or adapt the read input function (main.cpp).
For HSTI and HSTO, you can use any image from Van Hateren's image database. You might need to change read_input(), if the image format is different.

Please, let us know if you have more specific questions.
Regards,
Juan

**Comment by trinayan** [comment]
Hi,

Thanks for the information . What about for RSCT?. How do we get larger  inputs for that?


Best,
Trinayan

**Comment by el1goluj** [comment]
For RSCT and RSCD, the input file contains a list of flow vectors from a video frame with the format (x, y, vx, vy). It could be synthetically generated. (x, y) is the tail of the vector, and (vx, vy) is the head. They should be within frame dimensions.

**Comment by trinayan** [comment]
Ok thanks for the help

**Comment by el1goluj** [comment]
We have updated README in BFS, HSTI, HSTO, RSCD, RSCT, and SSSP, in order to include information related to this issue.

Regards,
Juan
