### ISSUE TITLE
CEDD issue

### ISSUE THREAD

**Issue by trinayan** [chai-benchmarks/chai#16]
Hi,

On my NVIDIA device the CEDD benchmark sometimes exits with an error: Invalid resource handle. The error is unpredictable and happens only at certain times. I dont know why. Might be thread race since it is totally indeterministic. Have you faced similar issues?

**Comment by el1goluj** [comment]
Hi Trinayan,

This is a known issue. We are trying to solve it. As you said, it only happens some times, so I hope you can still make your measurements.

Thanks,
Juan

**Comment by trinayan** [comment]
Yes I can still repeat the execution and make the measurements. One other thing I have noticed is all the other benchmarks have almost a constant execution time except SSSP. For some reason SSSP gives different execution times that can range to a difference of 50ms to at times 100ms without changing anything at all. Have you also observed this effect when benchmarking?

**Comment by el1goluj** [comment]
We have already found the problem with CEDD timing. It is a small issue with the timer that will be fixed shortly.
Regarding SSSP, I think that might be a separate issue. You could have started a new one. However, I have just run some experiments on an AMD Kaveri and an NVIDIA GTX 980, and I don’t see such difference in the execution time of different runs. The instability could be related to the platform you are using. Which GPU and CUDA version are you using?

**Comment by trinayan** [comment]
Hi ,
Thanks for getting back. I am using CUDA 8 on NVIDIA Jetson TX1. But i am using CUDA-D since system wide atomics is not supported.  Trying to see what is the issue here. Thank you.

**Comment by el1goluj** [comment]
I just tested on an NVIDIA Jetson TX1 with CUDA 7. As you said, kernel time in SSSP might be quite unstable. However, please, notice that the SSSP code in the repo only runs 1 warm-up run and 1 repetition. I would recommend you average several repetitions after several warm-up runs (for instance, ./sssp -w 5 -r 10). By doing so, I can see much more stable kernel times.

**Comment by trinayan** [comment]
O I see. That should be the case then. Thanks for the tip :)
