### ISSUE TITLE
Cuda version

### ISSUE THREAD

**Issue by trinayan** [chai-benchmarks/chai#9]
Hi,

Which cuda version is required to run these benchmarks? Also since there is cuda-U version I believe it is possible to run those on the jetson boards? 

Best,
Trinayan

**Comment by el1goluj** [comment]
Hi Trinayan,

CUDA-D runs on every NVIDIA GPU (c.c.>=2.0) and CUDA version (tested on CUDA 7.5). For CUDA-U, you will need NVIDIA Pascal and CUDA 8.0.

Best regards,
Juan

**Comment by trinayan** [comment]
Thanks for that. Just wondering about the performance metrics which is shown at the end. Is the kernel time the sum of executions on both devices or only on the gpu? I think it is both device from the code but just wanted to confirm.

**Comment by el1goluj** [comment]
The kernel time measurements in our ISPASS paper include CPU and GPU execution. Keep in mind that the execution on both devices is concurrent.
If you have more specific questions, please let us know.

**Comment by trinayan** [comment]
Thanks a lot. I wanted to know about the default partitioning options in each benchmark. Did you like try different options and made the ones which gave the best performance as default or was it based on other decision? Thank you

**Comment by lchang20** [comment]
The default partitioning option (-a, and default as 0.2) for data partitioning benchmarks are NOT the ones giving the best performance. It is arbitrarily preset to a reasonable value for one internal device. The benchmarks are written to evaluate multiple devices, so different data sets, languages, or devices might have different best partitions. To find the best, you can either sample different values, or enable dynamic partitioning (by giving "-a" a value not between 0.0 and 1.0).

**Comment by trinayan** [comment]
Ok thank you very much
